### ISSUE TITLE
1.21

### ISSUE THREAD

**Issue by Pie-Not-Lie** [agnor99/arrow-sprites#9]
Any plans to update the mod to 1.21? Love having the 2D-3D arrows :D

**Comment by Pie-Not-Lie** [comment]
Finally got some time to test: Seems like the latest build works in 1.21, with the big exception being a crash upon trying to render a tipped arrow:

Error: java.lang.NoSuchMethodError: 'net.minecraft.class_2487 net.minecraft.class_1799.method_7948()'

**Comment by worm-in-concrete** [comment]
A UFO arrived and shared this link here.
https://modrinth.com/resourcepack/trabens-3d-arrow-models
